apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-k8s-local
  namespace: argocd
spec:
  secretName: argocd-k8s-local-tls
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
    - argocd.k8s.local
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io